runtime: nodejs14

env_variables:
  NODE_ENV: "production"
  MONGO_USER: "Igor"
  MONGO_PASSWORD: "7yAFr5kaw6R1WpNo"
  MONGO_DEFAULT_DATABASE: "vezbadb"
  JWT_SECRET: "my-ultra-secure-and-ultra-long-secret"
  JWT_EXPIRES_IN: "90d"
  JWT_COOKIE_EXPIRES_IN: "90"
  EMAIL_USERNAME: "4b8f5ef2d0b5c9"
  EMAIL_PASSWORD: "b70a23a5cc8bc5"
  EMAIL_HOST: "smtp.mailtrap.io"
  EMAIL_PORT: "2525"
  EMAIL_FROM: "onebuck@io"
  SENDGRID_USERNAME: "apikey"
  SENDGRID_PASSWORD: "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"
  PRIVATEEMAIL_USER: "support@onebuck.store"
  PRIVATEEMAIL_PASS: "EsiMiDobar.4323"
  SENDGRID_API_KEY: "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"
  MJ_APIKEY_PUBLIC: "5a470645cdd22f262ee29af76f802c7a"
  MJ_APIKEY_PRIVATE: "cbe7bad7a51c4ad74c420917ea98e2ec"

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto